services:
  _defaults:
    public: true
  ps_demoextendsymfonyform.repository.reviewer:
    class: 'PrestaShop\Module\DemoHowToExtendSymfonyForm\Repository\ReviewerRepository'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
