demo_multistore:
    path: /demomultistoreform/configuration
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\DemoMultistoreForm\Controller\DemoMultistoreController::index'

demo_multistore_configuration_save:
    path: /demomultistoreform/configuration
    methods: [POST, PATCH]
    defaults:
        _controller: 'PrestaShop\Module\DemoMultistoreForm\Controller\DemoMultistoreController::saveConfiguration'

demo_multistore_create:
    path: /demomultistoreform/contentblock/create
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\DemoMultistoreForm\Controller\DemoMultistoreController::create'

demo_multistore_edit:
    path: /demomultistoreform/contentblock/{contentBlockId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\DemoMultistoreForm\Controller\DemoMultistoreController::edit'

demo_multistore_delete:
    path: /demomultistoreform/contentblock/{contentBlockId}/delete
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\DemoMultistoreForm\Controller\DemoMultistoreController::delete'

demo_multistore_toggle_status:
    path: /demomultistoreform/contentblock/{contentBlockId}/toggle
    methods: [POST]
    defaults:
        _controller: 'PrestaShop\Module\DemoMultistoreForm\Controller\DemoMultistoreController::toggleStatus'

demo_multistore_fixtures:
    path: /demomultistoreform/contentBlock/fixtures
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\DemoMultistoreForm\Controller\DemoMultistoreController::generateFixtures'
